spring.main.banner-mode: off

logging.level.org.springframework: ERROR


spring.sql.init.mode: always

spring.sql.init.platform: postgres

spring.datasource:

  url: jdbc:postgresql://localhost:5432/Camunda

#shareable postgres database: jdbc:postgres:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE

  username: postgres

  password: postgres

camunda.bpm.admin-user:

 id: demo

 password: demo

 firstName: Demo

 lastName: Demo

filter:

    create: All Tasks

#  default-serialization-format: application/json

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

spring:

  jpa:

    hibernate:

      ddl-auto: none

    properties:

      hibernate:

        dialect: org.hibernate.dialect.PostgreSQL81Dialect

        format_sql: true

    show-sql: true
server.port: 8085

